### PR TITLE
Add #[inline] to Shr for u64x2

### PR DESCRIPTION
**Pull request by bluss**

### CODE REVIEW

**Comment by bluss** [comment]
Found while working on simd siphash. This it works, but rotate: `x << l  | x >> (64 - l)` where `x: u64x2` compiles to operations in 64-bit registers at the moment.

**Comment by huonw** [comment]
Thanks!

> With this it works fine, but the operations to left rotate, x << l | x >> (64 - l) where x: u64x2 compiles to operations in 64-bit registers at the moment. 

Hm, could you clarify? With this patch, `(x << 3) | (x >> (64 - 3))` compiles to the following for me:

``` asm
    movdqa  %xmm0, %xmm1
    psllq   $3, %xmm1
    psrlq   $61, %xmm0
    por %xmm1, %xmm0
```

**Comment by bluss** [comment]
Aha that's cool. In this code, that doesn't happen https://github.com/bluss/rust-siphash-simd (WIP)

The core is around [src/lib.rs, line 257](https://github.com/bluss/rust-siphash-simd/blob/simd/src/lib.rs#L257-L292)

The rotations compile to `rol` on 64-bit registers. Not sure if that's even the main issue with this code (it's worse than the non-simd implementation still, but only 40% less throughput or so.)

[Perf annotation (disassembly)](https://gist.github.com/c97ab684b04c066989a9)

**Comment by bluss** [comment]
This code is not my invention, just transcribing [this](https://github.com/floodyberry/siphash/blob/master/siphash_sse2.c).

**Comment by huonw** [comment]
Hm, I suppose it's because LLVM is seeing the `unpacklo64` and understanding that the high u64s of the results aren't being used, so it would be "pointless" to rotate them. (I would assume that clang does the same thing on the C code, but maybe GCC handles it differently.)

**Comment by bluss** [comment]
Right. Surely it should be better if this is kept in wide registers like floodyberry (author) intended.

With black_box I can force it to generate the rotation like in your mini example :smile:, but it also has overhead...

**Comment by bluss** [comment]
Link to second sse2 impl https://github.com/floodyberry/supercop/blob/master/crypto_auth/siphash24/sse2-1/siphash.c

**Comment by huonw** [comment]
> Surely it should be better if this is kept in wide registers like floodyberry (author) intended.

That's not so obvious to me: it is the same number of instructions for both pieces of code. (Although I guess reducing data transfer overhead is desirable in this case. Either way, it's not immediately clear to me.)

**Comment by bluss** [comment]
Maybe I'm wasting my time! Here's some data that puts the simplest implementations above the specialized ones.. http://bench.cr.yp.to/impl-auth/siphash24.html

**Comment by bluss** [comment]
Implementation [little2](https://github.com/floodyberry/supercop/blob/master/crypto_auth/siphash24/little2/siphash.c)  (They're all cheating, assuming aligned data).

**Comment by huonw** [comment]
Huh, that's unfortunate.

**Comment by bluss** [comment]
Current result is  :(

```
test bench_bytes_4           ... bench:          25 ns/iter (+/- 1) = 160 MB/s
test bench_bytes_4_simd      ... bench:          36 ns/iter (+/- 1) = 111 MB/s
test bench_bytes_a_16        ... bench:          36 ns/iter (+/- 1) = 444 MB/s
test bench_bytes_a_16_simd   ... bench:          56 ns/iter (+/- 0) = 285 MB/s
test bench_bytes_b_32        ... bench:          48 ns/iter (+/- 1) = 666 MB/s
test bench_bytes_b_32_simd   ... bench:          80 ns/iter (+/- 1) = 400 MB/s
test bench_bytes_c_128       ... bench:         125 ns/iter (+/- 9) = 1024 MB/s
test bench_bytes_c_128_simd  ... bench:         207 ns/iter (+/- 3) = 618 MB/s
```

**Pull request merged**
